### ISSUE TITLE
Dates are stored without time zone

### ISSUE THREAD

**Issue by JakubTrousil** [jakubknejzlik/js-core-data#2]
Saving **03/19/2016 12:30:00+02** but in the database is **19.03.2016 12:30:00+00**

TimeSlot = model.defineEntity('TimeSlot', {
...
      dateFrom: 'date',
      dateTo: 'date',
...
});

Please repair.

Díky moc :) #sixteen

**Comment by jakubknejzlik** [comment]
from `03/19/2016 12:30:00+02` the timezone isn't recognized correctyl by Date function. If you use `03/19/2016 12:30:00+02:00` (append `:00`) it's parsed (and thus stored) ok.

**Comment by jakubknejzlik** [comment]
I recommend using ISO formatted string...it's safest way to work with dates. For example, this can happen in NodeJS (4.2.2 tested):
```
new Date('03/19/2016 12:30:00+02') => Sat Mar 19 2016 13:28:00 GMT+0100 (CET)
new Date('03/19/2016 12:30:00+02:00') => Sat Mar 19 2016 11:30:00 GMT+0100 (CET)
```

**Comment by jakubknejzlik** [comment]
I've also removed passing string to Date constructor and left it to the momentjs, which cause warnings, but make developer cautious.
