### ISSUE TITLE
Support for image data

### ISSUE THREAD

**Issue by Galderak** [jakubknejzlik/js-core-data#30]
Are there any plans to support image data ?

I'd like to store images using this framework but found no documentation for storing image data of any kind.

db.defineEntity('Image',{data:'BYTEA'}); < postgres example data type

**Comment by jakubknejzlik** [comment]
Hello @Galderak, you can use `data` type which is mapped to `BYTEA` in postgres store. Good point with the documentation.

**Comment by Galderak** [comment]
wow awesome thanks!

**Comment by jakubknejzlik** [comment]
glad to help! :)
